//  /lib/themes.ts
// all theme definitions

export interface Theme {
  name: string;
  bg: string;
  border: string;
  titleColor: string;
  textColor: string;
  iconColor: string;
  statColor: string;
  ringColor: string; // progress ring / donut stroke
  progressBarBg: string; // unfilled track
  progressBarFill: string; // filled track
}

export const themes: Record<string, Theme> = {
  // ─── Light ────────────────────────────────────────────────────────────────
  default: {
    name: "Default",
    bg: "#fffefe",
    border: "#e4e2e2",
    titleColor: "#2f80ed",
    textColor: "#434d58",
    iconColor: "#4c71a8",
    statColor: "#333",
    ringColor: "#2f80ed",
    progressBarBg: "#ddd",
    progressBarFill: "#2f80ed",
  },
  light: {
    name: "Light",
    bg: "#ffffff",
    border: "#e1e4e8",
    titleColor: "#24292e",
    textColor: "#586069",
    iconColor: "#586069",
    statColor: "#24292e",
    ringColor: "#0366d6",
    progressBarBg: "#e1e4e8",
    progressBarFill: "#0366d6",
  },
  minimal: {
    name: "Minimal",
    bg: "#ffffff",
    border: "#ffffff",
    titleColor: "#24292e",
    textColor: "#586069",
    iconColor: "#586069",
    statColor: "#24292e",
    ringColor: "#586069",
    progressBarBg: "#e1e4e8",
    progressBarFill: "#24292e",
  },
  // ─── Dark ─────────────────────────────────────────────────────────────────
  dark: {
    name: "Dark",
    bg: "#0d1117",
    border: "#30363d",
    titleColor: "#58a6ff",
    textColor: "#8b949e",
    iconColor: "#58a6ff",
    statColor: "#c9d1d9",
    ringColor: "#58a6ff",
    progressBarBg: "#21262d",
    progressBarFill: "#58a6ff",
  },
  radical: {
    name: "Radical",
    bg: "#141321",
    border: "#fe428e",
    titleColor: "#fe428e",
    textColor: "#a9fef7",
    iconColor: "#f8d847",
    statColor: "#ffffff",
    ringColor: "#fe428e",
    progressBarBg: "#2d2b55",
    progressBarFill: "#fe428e",
  },
  merko: {
    name: "Merko",
    bg: "#0a0f0b",
    border: "#1d4a2a",
    titleColor: "#abd200",
    textColor: "#68b587",
    iconColor: "#abd200",
    statColor: "#b7d364",
    ringColor: "#abd200",
    progressBarBg: "#1d4a2a",
    progressBarFill: "#abd200",
  },
  gruvbox: {
    name: "Gruvbox",
    bg: "#282828",
    border: "#504945",
    titleColor: "#fabd2f",
    textColor: "#ebdbb2",
    iconColor: "#fe8019",
    statColor: "#ebdbb2",
    ringColor: "#fabd2f",
    progressBarBg: "#504945",
    progressBarFill: "#b8bb26",
  },
  tokyonight: {
    name: "Tokyo Night",
    bg: "#1a1b27",
    border: "#414868",
    titleColor: "#70a5fd",
    textColor: "#38bdae",
    iconColor: "#bf91f3",
    statColor: "#cdd6f4",
    ringColor: "#70a5fd",
    progressBarBg: "#414868",
    progressBarFill: "#70a5fd",
  },
  onedark: {
    name: "One Dark",
    bg: "#282c34",
    border: "#3e4451",
    titleColor: "#61afef",
    textColor: "#abb2bf",
    iconColor: "#e5c07b",
    statColor: "#abb2bf",
    ringColor: "#61afef",
    progressBarBg: "#3e4451",
    progressBarFill: "#61afef",
  },
  cobalt: {
    name: "Cobalt",
    bg: "#193549",
    border: "#ffc600",
    titleColor: "#e683d9",
    textColor: "#0480ef",
    iconColor: "#ffc600",
    statColor: "#ffffff",
    ringColor: "#ffc600",
    progressBarBg: "#0b4f6c",
    progressBarFill: "#ffc600",
  },
  synthwave: {
    name: "Synthwave",
    bg: "#2b213a",
    border: "#e2d9f3",
    titleColor: "#e2d9f3",
    textColor: "#e2d9f3",
    iconColor: "#ef8539",
    statColor: "#e2d9f3",
    ringColor: "#ef8539",
    progressBarBg: "#49326b",
    progressBarFill: "#ef8539",
  },
  highcontrast: {
    name: "High Contrast",
    bg: "#000000",
    border: "#e7f216",
    titleColor: "#e7f216",
    textColor: "#ffffff",
    iconColor: "#e7f216",
    statColor: "#ffffff",
    ringColor: "#e7f216",
    progressBarBg: "#333",
    progressBarFill: "#e7f216",
  },
  dracula: {
    name: "Dracula",
    bg: "#282a36",
    border: "#6272a4",
    titleColor: "#ff79c6",
    textColor: "#f8f8f2",
    iconColor: "#bd93f9",
    statColor: "#f8f8f2",
    ringColor: "#ff79c6",
    progressBarBg: "#44475a",
    progressBarFill: "#bd93f9",
  },
  prussian: {
    name: "Prussian",
    bg: "#172f45",
    border: "#0d3b66",
    titleColor: "#38a0d4",
    textColor: "#cdd6f4",
    iconColor: "#38a0d4",
    statColor: "#cdd6f4",
    ringColor: "#38a0d4",
    progressBarBg: "#0d3b66",
    progressBarFill: "#38a0d4",
  },
  monokai: {
    name: "Monokai",
    bg: "#272822",
    border: "#75715e",
    titleColor: "#a6e22e",
    textColor: "#f8f8f2",
    iconColor: "#f92672",
    statColor: "#f8f8f2",
    ringColor: "#a6e22e",
    progressBarBg: "#3e3d32",
    progressBarFill: "#a6e22e",
  },
  vue: {
    name: "Vue",
    bg: "#273849",
    border: "#41b883",
    titleColor: "#41b883",
    textColor: "#ffffff",
    iconColor: "#41b883",
    statColor: "#ffffff",
    ringColor: "#41b883",
    progressBarBg: "#1f2d3d",
    progressBarFill: "#41b883",
  },
  // ─── Colourful ────────────────────────────────────────────────────────────
  algolia: {
    name: "Algolia",
    bg: "#050f2c",
    border: "#003dff",
    titleColor: "#00aeff",
    textColor: "#ffffff",
    iconColor: "#00aeff",
    statColor: "#ffffff",
    ringColor: "#003dff",
    progressBarBg: "#003dff",
    progressBarFill: "#00aeff",
  },
  github_dark: {
    name: "GitHub Dark",
    bg: "#0d1117",
    border: "#21262d",
    titleColor: "#79c0ff",
    textColor: "#8b949e",
    iconColor: "#58a6ff",
    statColor: "#c9d1d9",
    ringColor: "#79c0ff",
    progressBarBg: "#21262d",
    progressBarFill: "#79c0ff",
  },
  solarized_dark: {
    name: "Solarized Dark",
    bg: "#002b36",
    border: "#073642",
    titleColor: "#2aa198",
    textColor: "#839496",
    iconColor: "#268bd2",
    statColor: "#93a1a1",
    ringColor: "#2aa198",
    progressBarBg: "#073642",
    progressBarFill: "#2aa198",
  },
  solarized_light: {
    name: "Solarized Light",
    bg: "#fdf6e3",
    border: "#eee8d5",
    titleColor: "#2aa198",
    textColor: "#657b83",
    iconColor: "#268bd2",
    statColor: "#586e75",
    ringColor: "#2aa198",
    progressBarBg: "#eee8d5",
    progressBarFill: "#2aa198",
  },
  catppuccin_mocha: {
    name: "Catppuccin Mocha",
    bg: "#1e1e2e",
    border: "#45475a",
    titleColor: "#89b4fa",
    textColor: "#cdd6f4",
    iconColor: "#89dceb",
    statColor: "#cdd6f4",
    ringColor: "#89b4fa",
    progressBarBg: "#45475a",
    progressBarFill: "#89b4fa",
  },
  catppuccin_latte: {
    name: "Catppuccin Latte",
    bg: "#eff1f5",
    border: "#ccd0da",
    titleColor: "#1e66f5",
    textColor: "#4c4f69",
    iconColor: "#04a5e5",
    statColor: "#4c4f69",
    ringColor: "#1e66f5",
    progressBarBg: "#ccd0da",
    progressBarFill: "#1e66f5",
  },
  nord: {
    name: "Nord",
    bg: "#2e3440",
    border: "#3b4252",
    titleColor: "#88c0d0",
    textColor: "#d8dee9",
    iconColor: "#81a1c1",
    statColor: "#e5e9f0",
    ringColor: "#88c0d0",
    progressBarBg: "#3b4252",
    progressBarFill: "#88c0d0",
  },
  rose_pine: {
    name: "Rosé Pine",
    bg: "#191724",
    border: "#26233a",
    titleColor: "#ebbcba",
    textColor: "#e0def4",
    iconColor: "#9ccfd8",
    statColor: "#e0def4",
    ringColor: "#ebbcba",
    progressBarBg: "#26233a",
    progressBarFill: "#ebbcba",
  },
};

export type ThemeName = keyof typeof themes;

export function getTheme(name: string): Theme {
  return themes[name] ?? themes["default"];
}

export function themeNames(): string[] {
  return Object.keys(themes);
}